### ISSUE TITLE
Librification

### ISSUE THREAD

**Issue by V0ldek** [V0ldek/rsonpath#41]
**Is your feature request related to a problem? Please describe.**
Before adding more features we should commit to librification of `rsonpath`.

**Describe the solution you'd like**
We need a clear separation between the binary CLI tool and the underlying library. To complete that, we need to:

- [x] separate out a library crate, clean the dependencies of the library (#13, #37);
- [x] fix error handling (#38, #39);
- [x] and improve documentation (#40)
